#!/bin/bash

# 🚀 DAW Bookstore - Setup & Migration Script
# This script helps set up the project and prepare for migration

echo "📚 DAW Bookstore - Project Setup"
echo "=================================="
echo ""

# 1. Clean up old structure
echo "🧹 Cleaning old structure..."
# Note: Don't actually delete - just list what should be deleted
echo "   TODO: Delete these folders after migration:"
echo "   - src/hoang/DAW_BOOKSTORE_FE/"
echo "   - src/linh/DAW_BOOKSTORE_FE-dev/"
echo "   - Old package.json files"
echo ""

# 2. Install dependencies
echo "📦 Installing dependencies..."
npm install
echo "   ✅ Dependencies installed!"
echo ""

# 3. Show structure
echo "📁 Current project structure:"
echo ""
echo "src/"
echo "├── kiet/              ✅ KIET - Catalog"
echo "│   ├── pages/        (Home, Search, BookDetail)"
echo "│   ├── components/"
echo "│   └── services/"
echo "│"
echo "├── linh/              🔨 LINH - Auth (TODO)"
echo "│   ├── pages/        (LoginPage, SignupPage, ProfilePage, etc)"
echo "│   ├── components/   (AuthForm)"
echo "│   ├── contexts/     ✅ Ready"
echo "│   └── services/     ✅ Ready"
echo "│"
echo "├── hoang/             🔨 HOANG - Cart & Admin (TODO)"
echo "│   ├── pages/        (Cart, Checkout, Invoice, AdminDashboard)"
echo "│   ├── components/   (PrivateRoute, Layouts)"
echo "│   ├── contexts/     ✅ Ready"
echo "│   └── services/     ✅ Ready"
echo "│"
echo "├── shared/            📦 Shared Resources"
echo "│   ├── components/"
echo "│   ├── contexts/"
echo "│   ├── services/"
echo "│   └── types/"
echo "│"
echo "├── App.tsx            ✅ Routing hub (all routes)"
echo "└── ..."
echo ""

# 4. Show next steps
echo "🎯 NEXT STEPS:"
echo ""
echo "📖 KIET:"
echo "   1. Read: src/kiet/README.md"
echo "   2. Time: ~30 minutes"
echo "   3. Move pages to src/kiet/pages/"
echo ""
echo "📖 LINH:"
echo "   1. Read: src/linh/README.md"
echo "   2. Time: ~2-3 hours"
echo "   3. Move pages/components from DAW_BOOKSTORE_FE-dev"
echo "   4. Update imports"
echo ""
echo "📖 HOANG:"
echo "   1. Read: src/hoang/README.md"
echo "   2. Time: ~3-4 hours"
echo "   3. Move pages/components from DAW_BOOKSTORE_FE"
echo "   4. Update imports"
echo ""

# 5. Show commands
echo "🚀 COMMANDS:"
echo ""
echo "   Development:"
echo "   $ npm run dev           → Start dev server (localhost:5173)"
echo ""
echo "   Building:"
echo "   $ npm run build         → Build for production"
echo "   $ npm run preview       → Preview production build"
echo ""
echo "   Maintenance:"
echo "   $ npm run lint          → Run TypeScript lint"
echo "   $ npm run clean         → Clean dist folder"
echo ""

# 6. Show where old code is
echo "📦 OLD CODE LOCATIONS (to migrate):"
echo ""
echo "   Linh's code:"
echo "   src/linh/DAW_BOOKSTORE_FE-dev/src/pages/*"
echo "   src/linh/DAW_BOOKSTORE_FE-dev/src/components/*"
echo ""
echo "   Hoang's code:"
echo "   src/hoang/DAW_BOOKSTORE_FE/src/pages/*"
echo "   src/hoang/DAW_BOOKSTORE_FE/src/components/*"
echo ""

# 7. Show documentation
echo "📚 DOCUMENTATION:"
echo ""
echo "   MIGRATION_GUIDE.md      → Step-by-step instructions"
echo "   README_UNIFIED.md       → Project overview"
echo "   STRUCTURE_SUMMARY.md    → Quick reference"
echo "   src/kiet/README.md      → Kiet's module guide"
echo "   src/linh/README.md      → Linh's module guide"
echo "   src/hoang/README.md     → Hoang's module guide"
echo ""

echo "✅ Setup complete!"
echo ""
echo "🎉 You're ready to start development!"
echo ""
echo "👉 Next: Read your module's README and follow MIGRATION_GUIDE.md"
